### ISSUE TITLE
Rare weapon given incorrect holdType

### ISSUE THREAD

**Issue by IAmScorch** [IAmScorch/RNGRPG#1]
Rare weapon was dropped and generated. Weapon was a Long Sword which should have a holdType of 3 (2-Handed) but was given a hold type of 1 (Main Hand)

**Comment by dotxnc** [comment]
Long Sword and Short Sword are given a random hold type at runtime.
https://github.com/IAmScorch/RNGRPG/blob/304cd0fa34c86a374a1833736dcd7c7b6c2ba2c8/GameThingy/bandit.cpp#L367
https://github.com/IAmScorch/RNGRPG/blob/304cd0fa34c86a374a1833736dcd7c7b6c2ba2c8/GameThingy/bandit.cpp#L375

**Comment by IAmScorch** [comment]
> 

cool now I don't have to look for it myself when I go to fix it. Thanks bruh
